export interface RoomProperties {
  name: string;
  descriptions: string[];
  hotel: "HOT_BEACH_RESORT" | "HOT_BEACH_SUITE" | "JAPARATINGA";
  image?: string;
}

export const rooms = new Map<string, RoomProperties>([
  ['Suíte', { name: "Suite", descriptions: ["Apartamento com 2 cômodos, sendo um quarto com uma cama queen, smart TV e ar condicionado e uma sala com um sofá-cama de casal, um puff-cama de solteiro, smart TV e ar condicionado, além de varanda gourmet com churrasqueira, cozinha equipada com cooktop, microondas, geladeira e utensílios e um banheiro social.", "Oferece também acesso à internet via Wi-fi, tomadas 220W, kit de amenities e cofre eletrônico. Acomoda até 5 pessoas. Sem vista definida.", "Este quarto garante acesso livre ao Parque Aquático Hot Beach Olímpia e a Vila Guarani no período da hospedagem."], image: '/images/hot-beach/pdf-cotacao/rooms/suite.png', hotel: "HOT_BEACH_SUITE" }],
  ['Suíte Premier', { name: "Suíte Premier", descriptions: ["Apartamento com 3 cômodos, sendo um quarto com banheiro integrado, uma cama queen, smart TV e ar condicionado; um quarto com duas camas de solteiro, smart TV e ar condicionado; uma sala com um sofá-cama de casal, um puff-cama de solteiro, smart TV e ar condicionado, além de varanda gourmet com churrasqueira, cozinha equipada com cooktop, microondas, geladeira e utensílios e um banheiro social.", "Oferece também acesso à internet via Wi-fi, tomadas 220W, kit de amenities e cofre eletrônico. Acomoda até 7 pessoas. Sem vista definida.", "Este quarto garante acesso livre ao Parque Aquático Hot Beach Olímpia e a Vila Guarani no período da hospedagem."], image: '/images/hot-beach/pdf-cotacao/rooms/superior_premier.png', hotel: "HOT_BEACH_SUITE" }],
  ['Premier Família', { name: "Premier Família", descriptions: ["Quarto amplo com a vista para a cidade que contém 1 cama king e banheiro integrado, oferece também TV, ar-condicionado, frigobar, acesso à internet via Wi-fi, tomadas 220W, amenities, secador de cabelo e cofre eletrônico.", "Acomoda até 2 pessoas. Este quarto garante acesso livre ao Parque Aquático Hot Beach Olímpia e a Vila Guarani no período da hospedagem."], image: '/images/hot-beach/pdf-cotacao/rooms/premier_familia.png', hotel: "HOT_BEACH_RESORT" }],
  ['Superior Família', { name: "Superior Família", descriptions: ["Ar Condicionado /  Telefone /  Cofre /  Varanda / 220V / Acesso a internet Quarto amplo com vista para a cidade que contém 2 camas queen, sendo que uma delas pode ser separada em 2 camas de solteiro, e banheiro integrado.", "Oferece também TV, ar-condicionado, frigobar, acesso à internet via Wi-fi, tomadas 220W, amenities, secador de cabelo e cofre eletrônico, Acomoda até 4 pessoas.", "Este quarto garante acesso livre ao Parque Aquático Hot Beach Olímpia e a Vila Guarani no período da hospedagem."], image: '/images/hot-beach/pdf-cotacao/rooms/superior_familia.png', hotel: "HOT_BEACH_RESORT" }],
  ['Superior Casal PCD', { name: "Superior Casal PCD", descriptions: ["Apartamento com varanda com vista para a cidade adaptado para pessoas com deficiência e/ou mobilidade reduzida, possui uma cama king e banheiro integrado.", "Oferece também TV, ar-condicionado, frigobar, acesso à internet via Wi-fi, tomadas 220W, amenities, secador de cabelo e cofre eletrônico. Acomoda até 2 pessoas.", "Este quarto garante acesso livre ao Parque Aquático Hot Beach Olímpia e a Vila Guarani no período da hospedagem."], image: '/images/hot-beach/pdf-cotacao/rooms/superior_casal_pcd.png', hotel: "HOT_BEACH_RESORT" }],
  ['Superior Casal', { name: "Superior Casal", descriptions: ["Quarto amplo com a vista para a cidade que contém 1 cama king e banheiro integrado, oferece também TV, ar-condicionado, frigobar, acesso à internet via Wi-fi, tomadas 220W, amenities, secador de cabelo e cofre eletrônico.", "Acomoda até 2 pessoas. Este quarto garante acesso livre ao Parque Aquático Hot Beach Olímpia e a Vila Guarani no período da hospedagem."], image: '/images/hot-beach/pdf-cotacao/rooms/superior_casal.png', hotel: "HOT_BEACH_RESORT" }],
  ['Premier Casal', { name: "Premier Casal", descriptions: ["Quarto amplo com a vista para a cidade que contém 1 cama king e banheiro integrado, oferece também TV, ar-condicionado, frigobar, acesso à internet via Wi-fi, tomadas 220W, amenities, secador de cabelo e cofre eletrônico.", "Acomoda até 2 pessoas. Este quarto garante acesso livre ao Parque Aquático Hot Beach Olímpia e a Vila Guarani no período da hospedagem."], image: '/images/hot-beach/pdf-cotacao/rooms/premier-casal.png' , hotel: "HOT_BEACH_RESORT" }],
  ['SMART', { name: "Smart", descriptions: ["Suíte Smart do Japaratinga Lounge Resort."], hotel: "JAPARATINGA" }],
  ['STANDARD', { name: "Standard", descriptions: ["Perfeito pra acomodar até 3 pessoas. Sua configuração é de 1 cama King e 1 de solteiro. A vista da varanda pode ser frente-mar ou piscina, a depender da disponibilidade. Sem contar com a cafeteira Nespresso esperando por você!"], hotel: "JAPARATINGA" }],
  ['GARDEN SUITE', { name: "Garden Suite", descriptions: ["Suíte Garden Suite do Japaratinga Lounge Resort."], hotel: "JAPARATINGA" }],
  ['GARDEN EXCLUSIVE', { name: "Garden Exclusive", descriptions: ["Suíte Garden Exclusive do Japaratinga Lounge Resort."], hotel: "JAPARATINGA" }],
])